### PR TITLE
[MOD-2070] iOS: Add support for touchstart, touchend, touchcancel, touchmove

### PR DESCRIPTION
**Pull request by stephenfeather**
- unable to properly attribute because original ticket has disappeared

### CODE REVIEW

**Comment by ingo** [comment]
When we migrated the tickets, this one became private. I've made it public again. Thank you!

**Comment by muhammaddadu** [comment]
Hey @sfeather, could you please remove `ios/ti.paint-iphone-1.4.1.zip` from the PR.
FT **PASS**
CR **PASS**

**Comment by mano-mykingdom** [comment]
@sfeather - I'm using the module from your repo. But there is one issue with that. It fires the touch event but doesn't give the x & y axis values in the event object. I fixed it by replacing the fire event statement with process event statement.

Eg. - (void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event
{
    [self processTouchesMoved:touches withEvent:event];
}

**Comment by sfeather** [comment]
@mano-mykingdom,

Is that the only event not returning position?

**Comment by mano-mykingdom** [comment]
Yes it doesn't return the position of touch. For all events, touch start, end, move and cancel.

**Comment by hansemannn** [comment]
Hey @stephenfeather, I didn't see any activity in this PR for quite a long time. Do you still plan to migrate the PR so it returns the position in it? Otherwise it might not solve the use-case of the ones who need the coordinates in it. Let me know if I can help! :-)

**Pull request merged**
